# Generated by Django 4.2.6 on 2023-11-14 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automovil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=256)),
                ('modelo', models.CharField(max_length=256)),
                ('fabricacion', models.IntegerField()),
                ('cv', models.IntegerField(blank=True)),
                ('peso', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Camioneta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=256)),
                ('modelo', models.CharField(max_length=256)),
                ('fabricacion', models.IntegerField()),
                ('cv', models.IntegerField(blank=True)),
                ('peso', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Motocicleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=256)),
                ('modelo', models.CharField(max_length=256)),
                ('fabricacion', models.IntegerField()),
                ('cv', models.IntegerField(blank=True)),
                ('peso', models.IntegerField()),
            ],
        ),
    ]
