# Generated by Django 4.2.6 on 2023-11-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automovil',
            name='peso',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='camioneta',
            name='peso',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='motocicleta',
            name='cv',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='motocicleta',
            name='peso',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
